# Generated by Django 5.0.2 on 2024-03-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Una breve descripcion', null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank='True', help_text='Imagen referente a la categoria', null='True', upload_to='categorias'),
            preserve_default='True',
        ),
    ]
