# Generated by Django 5.0.2 on 2024-03-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0002_categoria_descripcion_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank='True', help_text='Imagen referente a la publicacion', null='True', upload_to='publicacion'),
            preserve_default='True',
        ),
    ]
