# Generated by Django 5.0.2 on 2024-03-24 04:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0003_publicacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen referente al evento', null=True, upload_to='eventos/')),
            ],
        ),
    ]
